[2023-02-01T18:59:27.251+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: CSV_DAG.convertCSVToJson scheduled__2023-02-01T00:30:00+00:00 [queued]>
[2023-02-01T18:59:27.349+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: CSV_DAG.convertCSVToJson scheduled__2023-02-01T00:30:00+00:00 [queued]>
[2023-02-01T18:59:27.367+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-01T18:59:27.369+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-02-01T18:59:27.376+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-01T18:59:28.147+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): convertCSVToJson> on 2023-02-01 00:30:00+00:00
[2023-02-01T18:59:28.267+0000] {standard_task_runner.py:55} INFO - Started process 13504 to run task
[2023-02-01T18:59:28.329+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'CSV_DAG', 'convertCSVToJson', 'scheduled__2023-02-01T00:30:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/csv.py', '--cfg-path', '/tmp/tmpel5vqoi6']
[2023-02-01T18:59:28.334+0000] {standard_task_runner.py:83} INFO - Job 26: Subtask convertCSVToJson
[2023-02-01T18:59:28.820+0000] {task_command.py:388} INFO - Running <TaskInstance: CSV_DAG.convertCSVToJson scheduled__2023-02-01T00:30:00+00:00 [running]> on host 06d8060e8530
[2023-02-01T18:59:29.135+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Kevin Chalmers
AIRFLOW_CTX_DAG_ID=CSV_DAG
AIRFLOW_CTX_TASK_ID=convertCSVToJson
AIRFLOW_CTX_EXECUTION_DATE=2023-02-01T00:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-01T00:30:00+00:00
[2023-02-01T18:59:29.186+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/csv.py", line 11, in CSVToJson
    df=pd.read_csv('/home/airflow/data.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/data.csv'
[2023-02-01T18:59:29.331+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=CSV_DAG, task_id=convertCSVToJson, execution_date=20230201T003000, start_date=20230201T185927, end_date=20230201T185929
[2023-02-01T18:59:29.426+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 26 for task convertCSVToJson ([Errno 2] No such file or directory: '/home/airflow/data.csv'; 13504)
[2023-02-01T18:59:29.672+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-01T18:59:29.762+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
